interface BehaviorOptions {
  antecedents: string[];
  consequences: string[];
}

export const behaviorSpecificOptions: { [behavior: string]: BehaviorOptions } = {
  // Physical Aggression
  "Hitting others": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Time out given",
      "Toy was removed",
      "Child was separated from others",
      "Activity was stopped",
      "Parent physically intervened",
      "Child was redirected to another activity",
      "Consequence was verbally explained",
      "Child was asked to apologize",
      "Child was taken to a different room",
      "Calm-down time was initiated",
      "Privilege was removed",
      "Safety check was performed",
      "Modeling of gentle behavior was provided"
    ]
  },
  "Kicking others": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Time out given",
      "Toy was removed",
      "Child was separated from others",
      "Activity was stopped",
      "Parent physically intervened",
      "Child was redirected to another activity",
      "Consequence was verbally explained",
      "Child was asked to apologize",
      "Child was taken to a different room",
      "Calm-down time was initiated",
      "Privilege was removed",
      "Safety check was performed",
      "Modeling of gentle behavior was provided"
    ]
  },
  "Biting": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Time out given",
      "Toy was removed",
      "Child was separated from others",
      "Activity was stopped",
      "Parent physically intervened",
      "Child was redirected to another activity",
      "Consequence was verbally explained",
      "Child was asked to apologize",
      "Child was taken to a different room",
      "Calm-down time was initiated",
      "Privilege was removed",
      "Safety check was performed",
      "Modeling of gentle behavior was provided"
    ]
  },
  "Throwing objects": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Time out given",
      "Toy was removed",
      "Child was separated from others",
      "Activity was stopped",
      "Parent physically intervened",
      "Child was redirected to another activity",
      "Consequence was verbally explained",
      "Child was asked to apologize",
      "Child was taken to a different room",
      "Calm-down time was initiated",
      "Privilege was removed",
      "Safety check was performed",
      "Modeling of gentle behavior was provided"
    ]
  },
  "Pushing": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Time out given",
      "Toy was removed",
      "Child was separated from others",
      "Activity was stopped",
      "Parent physically intervened",
      "Child was redirected to another activity",
      "Consequence was verbally explained",
      "Child was asked to apologize",
      "Child was taken to a different room",
      "Calm-down time was initiated",
      "Privilege was removed",
      "Safety check was performed",
      "Modeling of gentle behavior was provided"
    ]
  },
  "Pinching": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Time out given",
      "Toy was removed",
      "Child was separated from others",
      "Activity was stopped",
      "Parent physically intervened",
      "Child was redirected to another activity",
      "Consequence was verbally explained",
      "Child was asked to apologize",
      "Child was taken to a different room",
      "Calm-down time was initiated",
      "Privilege was removed",
      "Safety check was performed",
      "Modeling of gentle behavior was provided"
    ]
  },

  // Verbal Behaviors
  "Yelling or screaming": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Child was reminded to use indoor voice",
      "Screen or toy was taken away",
      "Parent responded with calm instruction",
      "Activity was paused",
      "Calm-down time was initiated",
      "Child was redirected to a quiet task",
      "Parent explained the consequence",
      "Child was asked to express themselves differently",
      "Parent provided a gentle verbal correction",
      "Privilege was removed",
      "Visual aid or cue card was offered",
      "Alternative behavior was modeled"
    ]
  },
  "Crying loudly": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Child was reminded to use indoor voice",
      "Screen or toy was taken away",
      "Parent responded with calm instruction",
      "Activity was paused",
      "Calm-down time was initiated",
      "Child was redirected to a quiet task",
      "Parent explained the consequence",
      "Child was asked to express themselves differently",
      "Parent provided a gentle verbal correction",
      "Privilege was removed",
      "Visual aid or cue card was offered",
      "Alternative behavior was modeled"
    ]
  },
  "Repetitive speech": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Child was reminded to use indoor voice",
      "Screen or toy was taken away",
      "Parent responded with calm instruction",
      "Activity was paused",
      "Calm-down time was initiated",
      "Child was redirected to a quiet task",
      "Parent explained the consequence",
      "Child was asked to express themselves differently",
      "Parent provided a gentle verbal correction",
      "Privilege was removed",
      "Visual aid or cue card was offered",
      "Alternative behavior was modeled"
    ]
  },
  "Using inappropriate words or profanity": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Child was reminded to use indoor voice",
      "Screen or toy was taken away",
      "Parent responded with calm instruction",
      "Activity was paused",
      "Calm-down time was initiated",
      "Child was redirected to a quiet task",
      "Parent explained the consequence",
      "Child was asked to express themselves differently",
      "Parent provided a gentle verbal correction",
      "Privilege was removed",
      "Visual aid or cue card was offered",
      "Alternative behavior was modeled"
    ]
  },
  "Refusal to speak": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Child was reminded to use indoor voice",
      "Screen or toy was taken away",
      "Parent responded with calm instruction",
      "Activity was paused",
      "Calm-down time was initiated",
      "Child was redirected to a quiet task",
      "Parent explained the consequence",
      "Child was asked to express themselves differently",
      "Parent provided a gentle verbal correction",
      "Privilege was removed",
      "Visual aid or cue card was offered",
      "Alternative behavior was modeled"
    ]
  },
  "Unusual vocal sounds": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Child was reminded to use indoor voice",
      "Screen or toy was taken away",
      "Parent responded with calm instruction",
      "Activity was paused",
      "Calm-down time was initiated",
      "Child was redirected to a quiet task",
      "Parent explained the consequence",
      "Child was asked to express themselves differently",
      "Parent provided a gentle verbal correction",
      "Privilege was removed",
      "Visual aid or cue card was offered",
      "Alternative behavior was modeled"
    ]
  },

  // Repetitive Behaviors
  "Hand flapping": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Rocking back and forth": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Spinning objects or self": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Tapping or hitting surfaces repeatedly": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Covering ears or eyes repeatedly": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Repetitively lining up objects": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },

  // Routine & Social Challenges
  "Refusing transition": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Resisting meals": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Refusing bedtime / leaving bed": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Running away / elopement": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Avoiding group interaction": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Refusing instructions": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  }
};

// Helper function to get shuffled options for a behavior
export function getShuffledOptions(behavior: string, questionType: 'antecedents' | 'consequences', currentSet: number = 0): string[] {
  const options = behaviorSpecificOptions[behavior];
  if (!options) {
    // Fallback options for behaviors not in our database
    const fallbackAntecedents = [
      "Asked to do something they didn't want to do",
      "Told to stop an activity they were enjoying",
      "Denied a request they made",
      "Asked to wait or be patient",
      "Told to follow instructions",
      "Asked to share or take turns",
      "Told to be quiet or calm down",
      "Asked to transition to a new activity",
      "Told to finish what they were doing",
      "Asked to help with a task"
    ];
    
    const fallbackConsequences = [
      "Time out was given",
      "Activity was stopped",
      "Privilege was removed",
      "Parent intervened",
      "Discussion about behavior",
      "Consequence was explained",
      "Calm down time was given",
      "Redirection to different activity",
      "Behavior was ignored",
      "Positive reinforcement for stopping"
    ];
    
    const fallbackOptions = questionType === 'antecedents' ? fallbackAntecedents : fallbackConsequences;
    const optionsPerSet = 5;
    const startIndex = (currentSet * optionsPerSet) % fallbackOptions.length;
    const endIndex = Math.min(startIndex + optionsPerSet, fallbackOptions.length);
    
    return fallbackOptions.slice(startIndex, endIndex);
  }

  const allOptions = options[questionType];
  const optionsPerSet = 5; // Show 5 options at a time
  const startIndex = (currentSet * optionsPerSet) % allOptions.length;
  const endIndex = Math.min(startIndex + optionsPerSet, allOptions.length);
  
  return allOptions.slice(startIndex, endIndex);
}

// Helper function to get total number of sets for a behavior
export function getTotalSets(behavior: string, questionType: 'antecedents' | 'consequences'): number {
  const options = behaviorSpecificOptions[behavior];
  if (!options) {
    // For fallback options, we have 10 options total, showing 5 per set
    return 2; // 10 options / 5 per set = 2 sets
  }

  return Math.ceil(options[questionType].length / 5);
} 