interface BehaviorOptions {
  antecedents: string[];
  consequences: string[];
}

export const behaviorSpecificOptions: { [behavior: string]: BehaviorOptions } = {
  // Physical Aggression
  "Hitting others": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Gave preferred item",
      "Gave preferred activity",
      "Gave verbal or physical attention (e.g., spoken to, patted, hugged)",
      "Demand or task stopped",
      "Delay or break before resuming task",
      "Removed from noisy/crowded area",
      "Allowed to avoid activity altogether",
      "No response given (ignored behavior)",
      "Maintained neutral facial expression",
      "Item taken away",
      "Activity ended early",
      "Privilege removed (e.g., screen time, toy, treat)",
      "Redirected to another activity",
      "Offered a choice between two acceptable options",
      "Prompted to use a coping strategy (e.g., deep breathing, counting, squeeze ball)",
      "Prompted to make an appropriate request or use a replacement behavior",
      "Modeled correct behavior for child to imitate",
      "Child cleaned up or repaired what was damaged",
      "Missed opportunity (e.g., snack, turn, game)",
      "Reviewed schedule or visual aid with child"  
    ]
  },
  "Kicking others": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Gave preferred item",
      "Gave preferred activity",
      "Gave verbal or physical attention (e.g., spoken to, patted, hugged)",
      "Demand or task stopped",
      "Delay or break before resuming task",
      "Removed from noisy/crowded area",
      "Allowed to avoid activity altogether",
      "No response given (ignored behavior)",
      "Maintained neutral facial expression",
      "Item taken away",
      "Activity ended early",
      "Privilege removed (e.g., screen time, toy, treat)",
      "Redirected to another activity",
      "Offered a choice between two acceptable options",
      "Prompted to use a coping strategy (e.g., deep breathing, counting, squeeze ball)",
      "Prompted to make an appropriate request or use a replacement behavior",
      "Modeled correct behavior for child to imitate",
      "Child cleaned up or repaired what was damaged",
      "Missed opportunity (e.g., snack, turn, game)",
      "Reviewed schedule or visual aid with child"  
    ]
  },
  "Biting": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Gave preferred item",
      "Gave preferred activity",
      "Gave verbal or physical attention (e.g., spoken to, patted, hugged)",
      "Demand or task stopped",
      "Delay or break before resuming task",
      "Removed from noisy/crowded area",
      "Allowed to avoid activity altogether",
      "No response given (ignored behavior)",
      "Maintained neutral facial expression",
      "Item taken away",
      "Activity ended early",
      "Privilege removed (e.g., screen time, toy, treat)",
      "Redirected to another activity",
      "Offered a choice between two acceptable options",
      "Prompted to use a coping strategy (e.g., deep breathing, counting, squeeze ball)",
      "Prompted to make an appropriate request or use a replacement behavior",
      "Modeled correct behavior for child to imitate",
      "Child cleaned up or repaired what was damaged",
      "Missed opportunity (e.g., snack, turn, game)",
      "Reviewed schedule or visual aid with child"
    ]
  },
  "Throwing objects": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Gave preferred item",
      "Gave preferred activity",
      "Gave verbal or physical attention (e.g., spoken to, patted, hugged)",
      "Demand or task stopped",
      "Delay or break before resuming task",
      "Removed from noisy/crowded area",
      "Allowed to avoid activity altogether",
      "No response given (ignored behavior)",
      "Maintained neutral facial expression",
      "Item taken away",
      "Activity ended early",
      "Privilege removed (e.g., screen time, toy, treat)",
      "Redirected to another activity",
      "Offered a choice between two acceptable options",
      "Prompted to use a coping strategy (e.g., deep breathing, counting, squeeze ball)",
      "Prompted to make an appropriate request or use a replacement behavior",
      "Modeled correct behavior for child to imitate",
      "Child cleaned up or repaired what was damaged",
      "Missed opportunity (e.g., snack, turn, game)",
      "Reviewed schedule or visual aid with child"
    ]
  },
  "Pushing": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Gave preferred item",
      "Gave preferred activity",
      "Gave verbal or physical attention (e.g., spoken to, patted, hugged)",
      "Demand or task stopped",
      "Delay or break before resuming task",
      "Removed from noisy/crowded area",
      "Allowed to avoid activity altogether",
      "No response given (ignored behavior)",
      "Maintained neutral facial expression",
      "Item taken away",
      "Activity ended early",
      "Privilege removed (e.g., screen time, toy, treat)",
      "Redirected to another activity",
      "Offered a choice between two acceptable options",
      "Prompted to use a coping strategy (e.g., deep breathing, counting, squeeze ball)",
      "Prompted to make an appropriate request or use a replacement behavior",
      "Modeled correct behavior for child to imitate",
      "Child cleaned up or repaired what was damaged",
      "Missed opportunity (e.g., snack, turn, game)",
      "Reviewed schedule or visual aid with child"
    ]
  },
  "Pinching": {
    antecedents: [
      "Sibling took their toy",
      "Peer hit or pushed them",
      "Was told to clean up toys",
      "Was told to get dressed",
      "iPad was taken away",
      "Candy or snack was denied",
      "Was told to wait their turn",
      "Screen time ended",
      "Lost a turn in a game",
      "Had to stop playing",
      "Loud noise occurred",
      "Someone entered their personal space",
      "Parent gave a toy to sibling",
      "Parent told them 'no'",
      "Had to share a toy",
      "Was moved to a different room",
      "Was told to sit down",
      "Was asked to eat food",
      "Clothes were put on",
      "Another child bumped into them",
      "Room became crowded",
      "Was told to stop an activity",
      "Timer went off"
    ],
    consequences: [
      "Gave preferred item",
      "Gave preferred activity",
      "Gave verbal or physical attention (e.g., spoken to, patted, hugged)",
      "Demand or task stopped",
      "Delay or break before resuming task",
      "Removed from noisy/crowded area",
      "Allowed to avoid activity altogether",
      "No response given (ignored behavior)",
      "Maintained neutral facial expression",
      "Item taken away",
      "Activity ended early",
      "Privilege removed (e.g., screen time, toy, treat)",
      "Redirected to another activity",
      "Offered a choice between two acceptable options",
      "Prompted to use a coping strategy (e.g., deep breathing, counting, squeeze ball)",
      "Prompted to make an appropriate request or use a replacement behavior",
      "Modeled correct behavior for child to imitate",
      "Child cleaned up or repaired what was damaged",
      "Missed opportunity (e.g., snack, turn, game)",
      "Reviewed schedule or visual aid with child"
    ]
  },

   // Verbal Behaviors
   "Yelling or screaming": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Responded to what they said",
      "Asked them to use a calmer voice or different words",
      "Ignored behavior and continued with task",
      "Redirected to a different topic or activity",
      "Ended the conversation or interaction",
      "Praised them when they spoke appropriately afterward",
      "Gave choices for how to communicate (e.g., write it down, show picture)",
      "Used humor or play to lighten the mood",
      "Modeled the words or tone you wanted them to use",
      "Repeated request or instructions calmly",
      "Left the area to give space"
    ]
  },
  "Crying loudly": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Responded to what they said",
      "Asked them to use a calmer voice or different words",
      "Ignored behavior and continued with task",
      "Redirected to a different topic or activity",
      "Ended the conversation or interaction",
      "Praised them when they spoke appropriately afterward",
      "Gave choices for how to communicate (e.g., write it down, show picture)",
      "Used humor or play to lighten the mood",
      "Modeled the words or tone you wanted them to use",
      "Repeated request or instructions calmly",
      "Left the area to give space"
    ]
  },
  "Repetitive speech": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Responded to what they said",
      "Asked them to use a calmer voice or different words",
      "Ignored behavior and continued with task",
      "Redirected to a different topic or activity",
      "Ended the conversation or interaction",
      "Praised them when they spoke appropriately afterward",
      "Gave choices for how to communicate (e.g., write it down, show picture)",
      "Used humor or play to lighten the mood",
      "Modeled the words or tone you wanted them to use",
      "Repeated request or instructions calmly",
      "Left the area to give space"
    ]
  },
  "Using inappropriate words or profanity": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Responded to what they said",
      "Asked them to use a calmer voice or different words",
      "Ignored behavior and continued with task",
      "Redirected to a different topic or activity",
      "Ended the conversation or interaction",
      "Praised them when they spoke appropriately afterward",
      "Gave choices for how to communicate (e.g., write it down, show picture)",
      "Used humor or play to lighten the mood",
      "Modeled the words or tone you wanted them to use",
      "Repeated request or instructions calmly",
      "Left the area to give space"
    ]
  },
  "Refusal to speak": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Responded to what they said",
      "Asked them to use a calmer voice or different words",
      "Ignored behavior and continued with task",
      "Redirected to a different topic or activity",
      "Ended the conversation or interaction",
      "Praised them when they spoke appropriately afterward",
      "Gave choices for how to communicate (e.g., write it down, show picture)",
      "Used humor or play to lighten the mood",
      "Modeled the words or tone you wanted them to use",
      "Repeated request or instructions calmly",
      "Left the area to give space"
    ]
  },
  "Unusual vocal sounds": {
    antecedents: [
      "Was told to be quiet",
      "Music or video was paused",
      "Denied request for a toy or item",
      "Screen was turned off",
      "Was asked to use words",
      "Asked to answer a question",
      "Was told to stop repeating words",
      "Another child shouted",
      "Was interrupted mid-sentence",
      "Parent walked away",
      "Was asked to clean up",
      "Timer went off",
      "Video ended",
      "Doorbell or phone rang",
      "Sibling made loud noise",
      "Was told to use inside voice",
      "Parent started talking to someone else",
      "Toy was removed",
      "Was told to speak up",
      "Was asked to say sorry",
      "Parent changed conversation topic"
    ],
    consequences: [
      "Responded to what they said",
      "Asked them to use a calmer voice or different words",
      "Ignored behavior and continued with task",
      "Redirected to a different topic or activity",
      "Ended the conversation or interaction",
      "Praised them when they spoke appropriately afterward",
      "Gave choices for how to communicate (e.g., write it down, show picture)",
      "Used humor or play to lighten the mood",
      "Modeled the words or tone you wanted them to use",
      "Repeated request or instructions calmly",
      "Left the area to give space"
    ]
  },
  "Pointing to an object": {
    antecedents: [
      "Desired item was out of reach",
      "Parent asked them to choose",
      "Offered multiple options",
      "Snack visible on counter",
      "Toy behind transparent container",
      "Parent looked confused about request",
      "Peer holding preferred toy",
      "Parent said 'show me'",
      "Item placed on high shelf",
      "Object hidden in cupboard",
      "Asked to indicate preference",
      "Loud environment limited speech",
      "Communication device unavailable",
      "Feeling shy around strangers",
      "Asked 'which one do you want?'",
      "Item presented but not handed over",
      "Parent unfamiliar with sign",
      "New activity choices displayed",
      "Parent paused to wait for response",
      "Item under table and visible"
    ],
    consequences: [
      "Parent gave indicated item",
      "Parent labeled the object verbally",
      "Parent praised pointing gesture",
      "Child received preferred snack",
      "Parent asked follow-up question",
      "Parent modeled spoken request",
      "Item added to visual schedule",
      "Peer shared toy",
      "Child repeated pointing",
      "Parent offered alternative item",
      "Parent delayed response",
      "Gesture ignored by caregiver",
      "Child grabbed item themselves",
      "Child switched focus",
      "Parent used sign for item",
      "Parent clarified misunderstanding",
      "Parent encouraged verbal attempt",
      "Item remained unavailable",
      "Parent prompted picture exchange",
      "Child smiled after receiving item"
    ]
  },
  "Using hand gestures to communicate": {
    antecedents: [
      "Noise level was high",
      "Parent asked for quiet hands",
      "Child lacked words for request",
      "Communicating with unfamiliar listener",
      "Peers talking simultaneously",
      "Asked to explain need",
      "Child excited about activity",
      "Speech device battery dead",
      "Parent distracted with task",
      "Child reminded to use gentle hands",
      "Asked to hurry",
      "Child wanted help opening item",
      "Sibling took toy",
      "Parent looked away briefly",
      "Child had mouth full",
      "Therapist prompted gesture use",
      "Child practicing new sign",
      "Asked to greet someone",
      "Speech therapy session ended",
      "Parent stressed and rushing"
    ],
    consequences: [
      "Parent acknowledged gesture",
      "Parent responded appropriately",
      "Requested item provided",
      "Parent labeled gesture verbally",
      "Gesture praised",
      "Caregiver modeled correct sign",
      "Child frustration reduced",
      "Gesture ignored unintentionally",
      "Parent asked for clarification",
      "Child repeated gesture",
      "Parent prompted speech attempt",
      "Sibling helped interpret",
      "Child moved closer to show",
      "Parent offered visual support",
      "Conversation continued smoothly",
      "Parent still misunderstood",
      "Child resorted to vocalization",
      "Behavior escalated",
      "Parent documented gesture in log",
      "Therapist reinforced use in session"
    ]
  },
  "Leading caregiver to item / place": {
    antecedents: [
      "Desired item in another room",
      "Child unable to name item",
      "Parent asked 'show me'",
      "Requested snack out of sight",
      "Child wanted to play outside",
      "Toy inside closet",
      "Parent busy cooking",
      "Communication breakdown occurred",
      "Child heard noise in room",
      "Sibling playing in bedroom",
      "Child needed help opening door",
      "Parent cleaning living room",
      "Item behind locked cabinet",
      "Child wanted tablet charging",
      "Parent on phone",
      "Child signaled thirst",
      "Favorite video on TV in den",
      "Parent just arrived home",
      "Child's routine time for activity",
      "Child spotted bird outside window"
    ],
    consequences: [
      "Parent followed child",
      "Caregiver discovered desired item",
      "Requested activity started",
      "Parent praised leading",
      "Parent labeled item verbally",
      "Item handed to child",
      "Caregiver opened door",
      "Alternative provided if unsafe",
      "Parent asked clarifying question",
      "Child smiled",
      "Parent encouraged verbalization",
      "Sibling joined activity",
      "Parent delayed response",
      "Request denied due to time",
      "Child cried when denied",
      "Parent set timer",
      "Item remained inaccessible",
      "Parent added item to list",
      "Child moved on",
      "Parent reinforced using words"
    ]
  },
  "Using PECS / picture cards": {
    antecedents: [
      "PECS book within reach",
      "Therapist session practicing PECS",
      "Asked to choose snack",
      "Communication partner new",
      "Child non-verbal at moment",
      "Device unavailable",
      "Parent prompted 'use your pictures'",
      "Desired toy on shelf",
      "Child learning new card",
      "Card missing from book",
      "Peer using PECS successfully",
      "Child hungry at lunchtime",
      "Parent offered two picture choices",
      "Visual schedule change",
      "Child frustrated by breakdown",
      "Noisy environment",
      "Teacher asked for request",
      "Sibling engaged with item",
      "Card fell on floor",
      "Parent withheld item to prompt"
    ],
    consequences: [
      "Parent exchanged picture for item",
      "Request honored",
      "Staff praised PECS use",
      "New card added",
      "Child smiled after success",
      "Parent modeled verbal label",
      "Card placed back in book",
      "Item denied due to limit",
      "Child repeated exchange",
      "Caregiver delayed response",
      "Card lost, causing frustration",
      "Teacher recorded data",
      "Peer imitated exchange",
      "Parent requested sentence strip",
      "Child used wrong card",
      "Correction provided gently",
      "Child screamed after denial",
      "Parent prompted bigger sentence",
      "Child moved to different request",
      "Therapist reinforced with praise"
    ]
  },
  "Using sign language": {
    antecedents: [
      "Sign language lesson earlier",
      "Parent asked 'how do you sign...?'",
      "Background noise high",
      "Child excited",
      "Desire for snack",
      "Communication device unavailable",
      "Child reminded to use sign",
      "Parent wearing mask",
      "Child practicing new signs",
      "Asked to greet someone",
      "Peer used sign",
      "Teacher asked question",
      "Child tired of talking",
      "Verbal attempt failed",
      "Parent insisted on manners",
      "Child wanted help",
      "Sibling playing loudly",
      "Therapist present",
      "Parent reading book together",
      "Child's mouth occupied"
    ],
    consequences: [
      "Parent acknowledged sign",
      "Requested item provided",
      "Caregiver praised signing",
      "Parent modeled spoken word",
      "Peer responded with sign",
      "Sign misunderstood",
      "Parent asked for repetition",
      "Child frustrated",
      "Parent prompted full sentence",
      "Child added facial expression",
      "Teacher reinforced in class",
      "Parent ignored accidentally",
      "Child switched to vocalization",
      "Sign recorded in communication log",
      "Parent delayed request",
      "Request denied due to policy",
      "Parent reinforced alternative sign",
      "Child smiled",
      "Peer learned new sign",
      "Parent signed thank you"
    ]
  },
  "Using AAC / speech device": {
    antecedents: [
      "Device within reach",
      "Device battery charged",
      "Prompted to use AAC",
      "Noise level high",
      "Device left in backpack",
      "Child wanted snack",
      "App needed update",
      "Parent asked question",
      "Screen brightness low",
      "Child excited",
      "Device turned off",
      "Therapist session using device",
      "Keyguard attached",
      "Message window cleared",
      "Child angry about delay",
      "Sibling using device",
      "Adult modeling AAC",
      "Child needed to greet visitor",
      "Choice presented on device",
      "Device on mount"
    ],
    consequences: [
      "Message spoken aloud",
      "Parent responded promptly",
      "Request granted",
      "Parent praised AAC use",
      "Device malfunctioned",
      "Delay in response",
      "Child repeated message",
      "Peer intrigued by device",
      "Parent modeled new vocabulary",
      "App crashed",
      "Child switched pages",
      "Device taken for charging",
      "Teacher recorded usage",
      "Request denied by caregiver",
      "Child frustrated",
      "Therapist reinforced with token",
      "Parent delayed response",
      "Sibling pressed button",
      "Volume adjusted",
      "Child smiled after success"
    ]
  },

  // Repetitive Behaviors
  "Hand flapping": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Allowed the behavior without comment",
      "Redirected to a different movement or activity",
      "Offered a sensory toy or fidget",
      "Joined in briefly to connect, then redirected",
      "Asked them to pause or take a break",
      "Provided comfort or reassurance",
      "Moved them to a quieter/less stimulating space",
      "Started a calming activity (e.g., deep breathing, music)",
      "Changed environment to remove possible triggers",
      "Offered a task that uses similar movement in a functional way (e.g., carrying items)",
      "Ignored and continued with the routine"
    ]
  },
  "Rocking back and forth": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Spinning objects or self": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Tapping or hitting surfaces repeatedly": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Covering ears or eyes repeatedly": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },
  "Repetitively lining up objects": {
    antecedents: [
      "Lights turned on/off",
      "Music started or stopped",
      "Was told to stop a repetitive action",
      "Toy was moved or cleaned up",
      "Entered a new room",
      "Loud noise occurred",
      "Was told to sit still",
      "Screen time began or ended",
      "Asked to clean up",
      "Asked to transition activities",
      "Someone began talking loudly",
      "Door opened or slammed",
      "Timer went off",
      "Room became crowded",
      "Toy was rearranged by someone",
      "Another child touched their item",
      "Clothing was adjusted",
      "Was asked to wait",
      "Meal or snack was served",
      "Someone sat nearby",
      "Object they were using was moved"
    ],
    consequences: [
      "Child was redirected to a new activity",
      "Calm-down time was initiated",
      "Parent modeled an alternative behavior",
      "Environment was changed (e.g. moved to quiet room)",
      "Child was given a fidget or sensory tool",
      "Activity was stopped",
      "Verbal reminder was given",
      "Consequence was explained",
      "Space was provided to regulate",
      "No direct response was given (behavior ignored)"
    ]
  },

  // Routine & Social Challenges
  "Refusing transition": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Gave a verbal prompt to continue with the activity",
      "Offered help or did the task together",
      "Allowed extra time before moving on",
      "Switched to a different task/activity",
      "Ended the activity early",
      "Gave praise or reward for completing part/all of it",
      "Gave a countdown before the next step (e.g., “2 more minutes”)",
      "Used a visual schedule or checklist to guide them",
      "Broke the task into smaller steps",
      "Let them choose between two activities",
      "Removed distractions before trying again",
      "Provided extra encouragement or reassurance"
    ]
  },
  "Resisting meals": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Refusing bedtime / leaving bed": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Running away / elopement": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Avoiding group interaction": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  },
  "Refusing instructions": {
    antecedents: [
      "Was asked to stop a game",
      "Was told to leave the park",
      "Screen was turned off",
      "Parent said it was bedtime",
      "Was told to get ready",
      "Was asked to eat food",
      "Was told to put on shoes",
      "Was asked to sit at the table",
      "Class or group activity started",
      "Was told to go home",
      "Toy was put away",
      "Was asked to come inside",
      "Timer went off",
      "Another child joined the room",
      "Backpack was packed",
      "Shoes were handed to them",
      "Was told to clean up toys",
      "Was asked to join a group",
      "Meal was served",
      "Parent opened the door",
      "Lights turned off",
      "Book or screen was closed"
    ],
    consequences: [
      "Extra time was provided before transition",
      "Activity was ended",
      "Calm-down time was initiated",
      "Parent explained next steps clearly",
      "Child was guided through the transition",
      "Child was redirected to new task",
      "Verbal encouragement was provided",
      "Visual schedule was shown",
      "Reward was delayed or removed",
      "Physical prompting was used",
      "Consequence was explained",
      "No response was given (behavior ignored)"
    ]
  }
};

// Helper function to get shuffled options for a behavior
export function getShuffledOptions(behavior: string, questionType: 'antecedents' | 'consequences', currentSet: number = 0): string[] {
  const options = behaviorSpecificOptions[behavior];
  if (!options) {
    // Fallback options for behaviors not in our database
    const fallbackAntecedents = [
      "Asked to do something they didn't want to do",
      "Told to stop an activity they were enjoying",
      "Denied a request they made",
      "Asked to wait or be patient",
      "Told to follow instructions",
      "Asked to share or take turns",
      "Told to be quiet or calm down",
      "Asked to transition to a new activity",
      "Told to finish what they were doing",
      "Asked to help with a task"
    ];
    
    const fallbackConsequences = [
      "Time out was given",
      "Activity was stopped",
      "Privilege was removed",
      "Parent intervened",
      "Discussion about behavior",
      "Consequence was explained",
      "Calm down time was given",
      "Redirection to different activity",
      "Behavior was ignored",
      "Positive reinforcement for stopping"
    ];
    
    const fallbackOptions = questionType === 'antecedents' ? fallbackAntecedents : fallbackConsequences;
    const optionsPerSet = 5;
    const startIndex = (currentSet * optionsPerSet) % fallbackOptions.length;
    const endIndex = Math.min(startIndex + optionsPerSet, fallbackOptions.length);
    
    return fallbackOptions.slice(startIndex, endIndex);
  }

  const allOptions = options[questionType];
  const optionsPerSet = 5; // Show 5 options at a time
  const startIndex = (currentSet * optionsPerSet) % allOptions.length;
  const endIndex = Math.min(startIndex + optionsPerSet, allOptions.length);
  
  return allOptions.slice(startIndex, endIndex);
}

// Helper function to get total number of sets for a behavior
export function getTotalSets(behavior: string, questionType: 'antecedents' | 'consequences'): number {
  const options = behaviorSpecificOptions[behavior];
  if (!options) {
    // For fallback options, we have 10 options total, showing 5 per set
    return 2; // 10 options / 5 per set = 2 sets
  }

  return Math.ceil(options[questionType].length / 5);
} 